### ISSUE TITLE
Investigate a device ID based upon the calibration numbers

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/MS5611#26]
The readProm() reads 7 values, which can be combined to a 32 bit ID.
Assuming these are unique per sensor, these could be combined in some hash (?) to form an unique ID.

**Comment by RobTillaart** [comment]
my ROM values (decimal)

0
42813
44132
26874
24506
32060
28365

**Comment by RobTillaart** [comment]
Created a develop branch  which implements a simple SHIFT XOR hashing of the PROM values.
PR = https://github.com/RobTillaart/MS5611/pull/27

Created an example **MS5611_promHash.ino** that generated 
```
MS5611 found: D963A70D
```

not really happy with the function name **getPromHash()** 
Although it is correct it is less understandable than e.g. **getDeviceID()**
which is in fact incorrect but more intuitive in its meaning...

**Comment by ratio-x** [comment]
my ROM values (decimal)

192
55102
52075
34758
31777
32430
28042

2120
58061
55931
36591
31881
32845
28228

+1 for naming this **getDeviceID()**

**Comment by RobTillaart** [comment]
Thanks. 
Numbers are different but also close so in HEX it might be more visible that the high byte is the same. 
This is no problem for the hash

**Comment by RobTillaart** [comment]
- Develop branch changed to **getDeviceID()**
- example program updated
- default address added (other issue)
- examples use default 0x77

**Comment by LyricPants66133** [comment]
What can this unique hash be used for?

**Comment by RobTillaart** [comment]
E.g. if you use offsets for the sensor to get correct figures, you can do that programmatically per sensor the right offset.
