### ISSUE TITLE
Reading temperature compensated values

### ISSUE THREAD

**Issue by roque-canales** [RobTillaart/MS5611#32]
Hello,

in your examples you not use the ms5611.reset function… while is the only one that read the calibration tables on the ms5611 memory.

can you tell me how to simple get temperature compensated pressure values?

For that we need to code this below?

in the setup:
Ms5611.begin
Ms5611.reset

in the main loop:
Ms5611.read
Ms5611.get temperature
Ms5611.get pressure

?

Does I forgot one thing?

thank you for for help.

rgds

**Comment by RobTillaart** [comment]
Thanks for the issue,
I moved it to the appropriate repository.

**Comment by roque-canales** [comment]
Hello Rob, thanks for marking this issue, can you send back an example that output temp compensated pressure values?

**Comment by RobTillaart** [comment]
Please note that **begin()** calls **reset()**

```cpp
bool MS5611::begin(TwoWire * wire)
{
  if ((_address < 0x76) || (_address > 0x77)) return false;
  _wire = wire;
  _wire->begin();
  if (! isConnected()) return false;

  return reset();   <<<<<<<<<<<<<<<<<<<<<<<<,
}
```

**Comment by roque-canales** [comment]
Sory to have missed that.

thank you !

**Comment by RobTillaart** [comment]
You're welcome!
