### ISSUE TITLE
Pressure values exactly half of expected value?

### ISSUE THREAD

**Issue by sathibault** [RobTillaart/MS5611#33]
Temperature is correct.  Pressure values are around 505 which is half what it should be.  Any ideas how this could happen?

**Comment by RobTillaart** [comment]
Thanks for this issue, 
I'll try to pick this up tomorrow. I do not recall seeing this before, also in other issues this is never mentioned.

Do you use 3V3 or 5V device?
Can you tell more about your setup?
code?

**Comment by sathibault** [comment]
It is connected to a Feather M4 Express with 3V3 power.  I'm calling the library in the default configuration with no arguments:
`MS5611.begin()` in setup and `MS5611.read()` and `MS5611.getPressure()` in loop.

**Comment by RobTillaart** [comment]
Had a quick look,

It might be in line 133 in ms5611.cpp

  C[3] = 3.90625E-3;      // TCS      = C[3] / 2^6

==>  

  C[3] = 0.015625      // TCS      = C[3] / 2^6

3.90625E-3 = 1/(2^8)

Can you give it a try?

(need to check if I still have a test sensor somewhere)

**Comment by RobTillaart** [comment]
mmm the above should give an error factor 4.
tomorrow I will dive into the datasheets

**Comment by sathibault** [comment]
Just in case it helps, these are the PROM values:
```
MS5611_LIB_VERSION: 0.3.8
140
38252
37147
24739
23894
32339
28498
```

**Comment by RobTillaart** [comment]
Thanks, those are device specific calibrations. Cant draw conclusions from them.

Q: do you have a link where you bought the device?
Just to check if the type is exactly the same.

A factor 2 can also be caused if a bit is missing in communication. 
Q: Do you have appropriate pull ups on data and clock line? .just to check.

**Comment by RobTillaart** [comment]
Good morning,

### Analysis
I have looked this morning into two documents, a datasheet and an application note. (AN520_004 www.meas-spec.com Aug. 09, 2011) and I noticed the following:

1. that the comment in my code **2^6** should be **2^8** according to the datasheet.
2. that the constants used in the algorithm to calculate the pressure differ between the two documents.

### Conclusions (so far)
Point 1 is easy to fix, and as the constants in the**code** are in line with the datasheet, and there was no factor 2 problem before I consider them correct. 

Point 2 is remarkable and indicates that there might be (at least) two different series of the sensor.

### Actions
1. I will make a test33 branch with the "other constants" and if you can test this with your sensor that would be great.
2. The constant 0 in EEPROM is the manufacturer code and is not used in the library. I will make a function to access it so it is possible to see if there are differences between these numbers.

To be continued.

**Comment by RobTillaart** [comment]
differences in the constants.
```cpp
                                          datasheet     |    appNote
  C[0] = 1;
  C[1] = 32768L;          //  SENSt1   = C[1] * 2^15    |    * 2^16
  C[2] = 65536L;          //  OFFt1    = C[2] * 2^16    |    * 2^17
  C[3] = 3.90625E-3;      //  TCS      = C[3] / 2^8     |    / 2^7
  C[4] = 7.8125E-3;       //  TCO      = C[4] / 2^7     |    / 2^6
  C[5] = 256;             //  Tref     = C[5] * 2^8     |    * 2^8
  C[6] = 1.1920928955E-7; //  TEMPSENS = C[6] / 2^23    |    / 2^23
```

C5 and C6 are for Temperature and they are the same.
The others are for pressure and they all differ a factor 2.
So it might explain your issue!

**Comment by RobTillaart** [comment]
Please download and try - https://github.com/RobTillaart/MS5611/tree/test33

**Comment by RobTillaart** [comment]
The test33 branch also contains updates for the coming 0.3.9 release.
- rp2040 in build
- changelog.md
- experimental functions **uint16_t getManufacturer()** and **uint16_t getSerialCode()**

These should not interfere with the changed constants.

**Comment by RobTillaart** [comment]
Added **setMathMode(mode)** to the branch to switch between the default mode and the mode with the constants used in the application notes. Although the latter are not tested yet I expect these to solve the issue.

**Comment by sathibault** [comment]
You did it, nice work!

**Comment by RobTillaart** [comment]
I'm not 100% happy yet with the API so there might be minor changes.
I'm thinking of putting the call to reset() within the setMsthMode() call + some param checking.

**Comment by RobTillaart** [comment]
Can you post the info of the type of device you have?
The n I can give it as example in the readme.md when to use the mathMode.

**Comment by RobTillaart** [comment]
@sathibault 
Refactored the library, now the mathMode is a parameter of **reset(mathMode = 0)**. Default the datasheet mode for backwards compatibility, option mathMode =1 for the factor 2 pressure correction. 
The separate functions to set the mode are gone (no need to call reset() after setting the mode anymore.
The interface of the lib is almost identical so most people won't notice. 
And for those who need the factor2 correction, they only need to add one call in the setup() of their code.

I will merge later today

**Comment by sathibault** [comment]
> Can you post the info of the type of device you have? The n I can give it as example in the readme.md when to use the mathMode.

I don't really have any detail on it.  It came from a drone development kit and seems to be a custom board.  There's nothing readable on the chip.  The PROM reg 0 is 140.  Not sure if that is an indicator or not.

**Comment by RobTillaart** [comment]
> I don't really have any detail on it. 

Thanks for checking, most important is that the sensor now works as intended and that I have docs that describe the math.
if you are interested - https://www.amsys-sensor.eu/sheets/amsys.fr.an520_e.pdf

> The PROM reg 0 is 140. Not sure if that is an indicator or not.

I have 5 or 6 dumps and they are all different. I do not have any clue what reg 0 means.
The other regs are at least in the same orde of magnitude so they are calibration data.

**Comment by ThisIsntTheWay** [comment]
> Can you post the info of the type of device you have? The n I can give it as example in the readme.md when to use the mathMode.

I've had the same issue whilst using a GY-63 breakout and implementing the math as described by the [MS5611-01BA03 datasheet](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5611-01BA03%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS5611-01BA03_B3.pdf%7FCAT-BLPS0036).  
Sadly I cannot read the text on the sensor itself; It's way too small.

**Comment by RobTillaart** [comment]
@ThisIsntTheWay 

> I've had the same issue

Does the mathMode flag solves your problem? See readme.md

----

> Sadly I cannot read the text on the sensor itself; It's way too small.

Mobile phones often can zoom in just enough, rotate a bit to get right reflection.

**Comment by ThisIsntTheWay** [comment]
> Does the mathMode flag solves your problem? See readme.md

Yeah it did, I forgot to mention that the app note constants solved the issue 😛  

Good idea with the phone, I was able to make out the the following when zooming in:   
```
MEAS
560702BA03
M(1/I)3290
```

The math in its [datasheet](https://www.farnell.com/datasheets/2917207.pdf), page 9, seems to use the same constants as mentioned in the app notes.

**Comment by RobTillaart** [comment]
Good to hear it is solved!
