### ISSUE TITLE
Avoid preprocessor directive names similar to class names MS5611

### ISSUE THREAD

**Issue by brightproject** [RobTillaart/MS5611#41]
I use two devices with different sensors - `Bosch BMP390` and `MEAS Switzerland MS5611`

```
#ifdef MS5611
#include <MS5611.h>
#endif
#ifdef BMP390
#include <Adafruit_Sensor.h>
#include "Adafruit_BMP3XX.h"
#endif

#ifdef MS5611
MS5611 STATIC(0x76); //  0x76 = CSB to VCC
MS5611 PRESSURE(0x77); //  0x77 = CSB to GND
#endif
#ifdef BMP390
Adafruit_BMP3XX STATIC;
Adafruit_BMP3XX PRESSURE;
#endif
```

Imagine my surprise when the compiler gave me an error.

> MS5611.h:60:3: warning: 'explicit(bool)' only available with '-std=c++20' or '-std=gnu++20' [-Wc++20-extensions]
>    60 |   explicit MS5611(uint8_t deviceAddress = MS5611_DEFAULT_ADDRESS, TwoWire *wire = &Wire);

I was already thinking about rewriting the `I2C` bus initialization like here

> https://github.com/adafruit/Adafruit_BMP3XX/blob/33b19ccb6d11aeda4e433d3df5ed40a75bb0ee4a/Adafruit_BMP3XX.h#L45

But the problem turned out to be my carelessness and lack of knowledge `C++`.
You just don't need to assign the same name to the `define` as the library name.
Now used

> #define MS5611_SENSOR

And problem resolved🙂

My opinion is that the library class should be renamed, and therefore made `unique`, so that under no circumstances could it be replaced using the `#DEFINE` preprocessor directive.

I ask the @RobTillaart to add the necessary `flag` to this issue, in case someone encounters the same error when compiling the code.

**P.S**
Also, in the process of searching for problems with the code, I changed the design

> https://github.com/RobTillaart/MS5611/blob/0024c78ec949a14be9b6adca0d9cba18275e744a/MS5611.h#L1

To a modern one

> #ifndef __MS5611_H__
> #define __MS5611_H__
> ...
> #endif // __MS5611_H__

**Comment by RobTillaart** [comment]
Thanks for the issue,
Will get into it asap, might take a few days.

**Comment by RobTillaart** [comment]
> the necessary flag to this issue,...

You might change the title of the issue to be more descriptive.

**Comment by RobTillaart** [comment]
@brightproject 

The ```#pragma once``` versus ```#ifndef``` discussion is one with several arguments. 

pragma once is not part of C/C++ standard however it is supported by almost all compilers. Some might do a better job than others. The number of issues I got with respect to file guards is very low, maybe two in almost 15 years.

There ifndef construct works equally well and has its own set of problems and features. In practice it is therefor not better/worse than pragma once. Different files can define the same guard tag, causing an unexpected/unwanted collision.

The only feature ifndef has is that the compiler still reads/parses the file until the endif. So the ifndef construct allows to guard a partial file, either from the begin, halfway or at the end.

For me pragma once is mostly about ease of use, just one line and the whole file is guarded.

**Comment by RobTillaart** [comment]
Good rename of the title 👍

**Comment by RobTillaart** [comment]
As the story is clear I close this issue, as closed issues can still be found.

Again thanks for sharing your insights
